bot:
  token: !ENV "BOT_TOKEN"

  prefix     : &BOT_PREFIX ";"
  name       : &BOT_NAME "Itk Bot"
  description: "知らない..."

  owner: &BOT_OWNER 523755296242270210
  moderators:
    - *BOT_OWNER
    - 590430031281651722 # Traveler
    - 546614210243854337 # Juxta
    - 501782173364518912 # Raticate

  main_guild: &main_guild 669934356172636199
  test_guild: &test_guild 725295821456801842

  test_channel       : 725295821456801845
  main_channel       : 669934356172636208
  log_channel        : 838402956863733820
  chat_backup_channel: 741556551143391323
  edit_backup_channel: 745569697013039105

  ignore_channels:
    - 675956755112394753
    - 703215004807069737
  ignore_keywords:
    - "save"
    - "url"
    - "programming"
    - "q"
    - "p"
    - "ps"
    - "pt"
    - "np"
    - "fs"
    - "dc"

  image_folder: &IMAGE_FOLDER "./images/"

  mongo_host             : !ENV "MONGO_HOST"
  sauce_nao_key          : !ENV "SAUCE_NAO_KEY"
  custom_search_engine_id: !ENV "CUSTOM_SEARCH_ENGINE_ID"
  google_search_api_keys : !ENV
    - "GOOGLE_SEARCH_API_KEY_1"
    - "GOOGLE_SEARCH_API_KEY_2"
    - "GOOGLE_SEARCH_API_KEY_3"
  google_search_options:
    c2coff: 0             # Chinese results
    hl    : 'zh-TW'       # Interface lang
    gl    : 'tw'          # Geographic location
    lr    : 'lang_zh-TW'  # Result lang
    safe  : 'off'         # Safe mode

log:
  sentry_dsn: !ENV "SENTRY_DSN"

  log_level: 5

  log_format : "%(asctime)s | %(name)s | %(levelname)-9s | %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file_path  : "./logs"
  file_name  : "discord_bot.log"

  coloredlogs:
    styles:
      trace:
        color: 246
      debug:
        color: 28
      warning:
        color: 220
      critical:
        background: "red"

styles:
  colors:
    red         : &red 0xDB4A30
    teal        : &teal 0x0F7173
    blue        : &blue 0x5386E4
    pink        : &pink 0xDA627D
    cyan        : &cyan 0x66999B
    green       : &green 0x8EA604
    yellow      : &yellow 0xE9DF00
    purple      : &purple 0x4D0D43
    navy_blue   : &navy_blue 0x273469
    dark_teal   : &dark_teal 0x113537
    blue_gray   : &blue_gray 0x7798AB
    dark_green  : &dark_green 0x34403A
    olive_green : &olive_green 0xB1B695
    light_yellow: &light_yellow 0xFCD992

  emojis:
    i11_chiwawa: &i11_chiwawa "<:i11_chiwawa:783346447319171075>"

    helen_1  : &helen_1 "<:helen_1:838343516743532554>"
    helen_2  : &helen_2 "<:helen_2:838343516895182848>"
    helen_3  : &helen_3 "<:helen_3:838343516865298442>"
    helen_4  : &helen_4 "<:helen_4:838343516374564885>"
    helen_5  : &helen_5 "<:helen_5:838343517033725992>"
    helen_6  : &helen_6 "<:helen_6:838343517037133847>"
    helen_7  : &helen_7 "<:helen_7:838343517037264896>"
    helen_art: &helen_art "<:helen_art:838378914472263701>"

    helens:
      - *helen_1
      - *helen_2
      - *helen_3
      - *helen_4
      - *helen_5
      - *helen_6
      - *helen_7

    thonk: &thonk "<:thonk:781092810572562432>"

    # Pepe
    bongo_pepe        : &bongo_pepe "<a:bongo_pepe:823225627259699237>"
    pepe_coffee       : &pepe_coffee "<:pepe_coffee:823454537305030657>"
    pepe_coin         : &pepe_coin "<a:pepe_coin:823235418529988659>"
    pepe_cross        : &pepe_cross "<:pepe_cross:823453075095158804>"
    pepe_crown_flip   : &pepe_crown_flip "<a:pepe_crown_flip:823468015412707338>"
    pepe_depressed    : &pepe_depressed "<:pepe_depressed:823472210349391873>"
    pepe_facepalm     : &pepe_facepalm "<:pepe_facepalm:823196602122108959>"
    pepe_hands        : &pepe_hands "<:pepe_hands:823446764378914836>"
    pepe_hmm          : &pepe_hmm "<:pepe_hmm:823444896115458060>"
    pepe_hypers       : &pepe_hypers "<:pepe_hypers:838345805323960330>"
    pepe_monkaS       : &pepe_monkaS "<:pepe_monkaS:823445833735208980>"
    pepe_monkaSTEER   : &pepe_monkaSTEER "<a:pepe_monkaSTEER:823470686650499092>"
    pepe_nitro        : &pepe_nitro "<a:pepe_nitro:823467488930037761>"
    pepe_nopes        : &pepe_nopes "<a:pepe_nopes:823465237311127562>"
    pepe_pog_champ    : &pepe_pog_champ "<:pepe_pog_champ:838461034275799061>"
    pepe_px           : &pepe_px "<a:pepe_pixel:823467770389331978>"
    pepe_px_xmas      : &pepe_px_xmas "<a:pepe_pixel_christmas:823470432803356683>"
    pepe_saber        : &pepe_saber "<a:pepe_saber:823467708217425930>"
    pepe_sad          : &pepe_sad "<:pepe_sad:823456479591530507>"
    pepe_sadge        : &pepe_sadge "<:pepe_sadge:823456522696392705>"
    pepe_simp         : &pepe_simp "<:pepe_simp:823448668198797313>"
    pepe_sus          : &pepe_sus "<:pepe_sus:823451080942682153>"
    rainbow_pepe_angry: &rainbow_pepe_angry "<a:rainbow_pepe_angry:823463476440727562>"
    rainbow_pepe_happy: &rainbow_pepe_happy "<a:rainbow_pepe_happy:823463330131738624>"

  reactions:
    prev_page : "<:prev_page:805002492848767017>"
    next_page : "<:next_page:805002492525805589>"
    first_page: "<:first_page:806497548343705610>"
    last_page : "<:last_page:806497548558532649>"
    check_mark: "\u2705"
    cross_mark: "\u274E"
    numbers:
      - "1\u20E3"
      - "2\u20E3"
      - "3\u20E3"
      - "4\u20E3"
      - "5\u20E3"
      - "6\u20E3"
      - "7\u20E3"
      - "8\u20E3"
      - "9\u20E3"
    letters:
      - "\u1F1E6"
      - "\u1F1E7"
      - "\u1F1E8"
      - "\u1F1E9"
      - "\u1F1EA"
      - "\u1F1EB"
      - "\u1F1EC"
      - "\u1F1ED"
      - "\u1F1EE"
      - "\u1F1EF"
      - "\u1F1F0"
      - "\u1F1F1"
      - "\u1F1F2"
      - "\u1F1F3"
      - "\u1F1F4"
      - "\u1F1F5"
      - "\u1F1F6"
      - "\u1F1F7"
      - "\u1F1F8"
      - "\u1F1F9"
      - "\u1F1FA"
      - "\u1F1FB"
      - "\u1F1FC"
      - "\u1F1FD"
      - "\u1F1FE"
      - "\u1F1FF"

help_messages:
  help:
    title      : "看看是哪個小可憐忘記指令怎麼打啦？"
    description: ".help <指令> 可以查看更詳細的說明"
    color      : *light_yellow
    author     : *BOT_NAME
    footer     : "那個...窩不知道"
    fields:
      - - !JOIN [*BOT_PREFIX, "bzz"]
        - "抽籤"
      - - !JOIN [*BOT_PREFIX, "tdbzz"]
        - "當日運勢"
      - - !JOIN [*BOT_PREFIX, "choose"]
        - "從選項中隨機挑選"
      - - !JOIN [*BOT_PREFIX, "poll"]
        - "發起投票"
      - - !JOIN [*BOT_PREFIX, "roll"]
        - "抽...數字？"
      - - !JOIN [*BOT_PREFIX, "is"]
        - "根據回覆、連結、附件搜尋圖片"
      - - !JOIN [*BOT_PREFIX, "cue"]
        - "另一個奇怪的錯字全集"
      - - !JOIN [*BOT_PREFIX, "emoji"]
        - "觀看伺服器的表符使用率"
      - - !JOIN [*BOT_PREFIX, "pin"]
        - "奇怪的發言大全"
      - - !JOIN [*BOT_PREFIX, "clean"]
        - "清除訊息"
  bzz:
    title      : !JOIN [*BOT_PREFIX, "bzz"]
    description: "別名：無"
    color      : *teal
    author     : *BOT_NAME
    footer     : !JOIN ["今天要來點小", *i11_chiwawa, "嗎？"]
    fields:
      - - !JOIN [*BOT_PREFIX, "bzz"]
        - "沒什麼特別的，就是回覆給你一個運勢"
  tdbzz:
    title      : !JOIN [*BOT_PREFIX, "tdbzz"]
    description: "別名：無"
    color      : *blue
    author     : *BOT_NAME
    footer     : !JOIN ["今天要來點大", *i11_chiwawa, "嗎？"]
    fields:
      - - !JOIN [*BOT_PREFIX, "tdbzz"]
        - "回覆給你一個運勢，此運勢會在 00:00 (GMT+8) 時重置"
  choose:
    title      : !JOIN [*BOT_PREFIX, "choose [選項]..."]
    description: "別名：`ch`"
    color      : *pink
    author     : *BOT_NAME
    footer     : "狗才做選擇，汪"
    fields:
      - - !JOIN [*BOT_PREFIX, "choose"]
        - "從選項內隨機挑選"
      - - "[選項]..."
        - "可自由輸入選項，以空格區隔（選項含空格可以''括起）"
  poll:
    title      : !JOIN [*BOT_PREFIX, "poll <標題> [選項]..."]
    description: "別名：`vote`"
    color      : *cyan
    author     : *BOT_NAME
    footer     : "這是人民的意志，人民的法槌！"
    fields:
      - - !JOIN [*BOT_PREFIX, "poll"]
        - "以標題及選項發起投票"
      - - "<標題>"
        - "當次投票的標題、主題"
      - - "[選項]..."
        - "可輸入最多 20 個的選項，以空格區隔（選項含空格可以''括起）"
  pin:
    title      : !JOIN [*BOT_PREFIX, "pin [成員]"]
    description: "別名：無"
    color      : *green
    author     : *BOT_NAME
    footer     : "你看看你們都講了些什麼"
    fields:
      - - !JOIN [*BOT_PREFIX, "pin"]
        - "總之就是從釘選中隨機選出一句奇怪的話"
      - - "[成員]"
        - "~~你要迫害的人~~"
  cue:
    title      : !JOIN [*BOT_PREFIX, "cue [成員] [位置]"]
    description: "別名：`c`"
    color      : *yellow
    author     : *BOT_NAME
    footer     : "在啦幹"
    fields:
      - - !JOIN [*BOT_PREFIX, "cue"]
        - "各位的錯字都在這裡了 :)"
      - - "[成員]"
        - "指定成員，不填入則為隨機"
      - - "[位置]"
        - "指定位置，不填入則為隨機"
      - - "子指令"
        - "`add`|`delete`|`list`"
    add:
      title      : !JOIN [*BOT_PREFIX, "cue add <成員> <語句>"]
      description: "別名：`a`"
      color      : *yellow
      author     : *BOT_NAME
      footer     : "我猜又是花花"
      fields:
        - - !JOIN [*BOT_PREFIX, "add"]
          - "看看又是誰打錯字了"
        - - "<成員>"
          - "錯字仔"
        - - "<語句>"
          - "總之就是錯字"
    delete:
      title      : !JOIN [*BOT_PREFIX, "cue delete <成員> <語句|位置>"]
      description: "別名：`del`|`remove`|`r`"
      color      : *yellow
      author     : *BOT_NAME
      footer     : "這是一場美麗的誤會"
      fields:
        - - !JOIN [*BOT_PREFIX, "delete"]
          - "看看又是誰打錯字了"
        - - "<成員>"
          - "不是錯字仔的錯字仔"
        - - "<語句|位置>"
          - "透過指定語句或位置來刪除語錄"
    list:
      title      : !JOIN [*BOT_PREFIX, "cue list <成員>"]
      description: "別名：`l`"
      color      : *yellow
      author     : *BOT_NAME
      footer     : "國文老師現在很火"
      fields:
        - - !JOIN [*BOT_PREFIX, "list"]
          - "列出錯字仔的所有錯字"
        - - "<成員>"
          - "沒有錯就是那個錯字仔"
  emoji:
    title      : !JOIN [*BOT_PREFIX, "emoji"]
    description: "別名：`emo`|`e`"
    color      : *purple
    author     : *BOT_NAME
    footer     : "驚訝貓貓"
    fields:
      - - !JOIN [*BOT_PREFIX, "emoji"]
        - "列出伺服器表符的使用次數"
      - - "子指令"
        - "`rank`|`reset`"
    rank:
      title      : !JOIN [*BOT_PREFIX, "emoji rank"]
      description: "別名：`r`"
      color      : *purple
      author     : *BOT_NAME
      footer     : "驚訝貓貓 2.0（？"
      fields:
        - - !JOIN [*BOT_PREFIX, "emoji rank"]
          - "其實就跟單打 emoji 一樣"
    reset:
      title      : !JOIN [*BOT_PREFIX, "emoji reset"]
      description: "別名：無"
      color      : *purple
      author     : *BOT_NAME
      footer     : "驚訝貓貓 3.0（？？？"
      fields:
        - - !JOIN [*BOT_PREFIX, "emoji reset"]
          - "重設已經紀錄的使用次數"
  clean:
    title      : !JOIN [*BOT_PREFIX, "clean [天數]"]
    description: "別名：無"
    color      : *blue_gray
    author     : *BOT_NAME
    footer     : "黑人消失.gif"
    fields:
      - - !JOIN [*BOT_PREFIX, "clean"]
        - "清除機器人的訊息"
      - - "[天數]"
        - "指定要清除的天數，若未指定則為一天"
  image_search:
    title      : !JOIN [*BOT_PREFIX, "image_search [網址]..."]
    description: "別名：`is`"
    color      : *blue_gray
    author     : *BOT_NAME
    footer     : "is 怪欸"
    fields:
      - - !JOIN [*BOT_PREFIX, "image_search"]
        - "依序抓取回覆訊息的附件 → 指令訊息的附件 → 指令訊息的連結，並進行搜尋（上限為 6 附件）"
      - - "[網址]"
        - "圖片網址，須為`.jpg`|`.png`|`.jpeg`結尾"

events:
  helen_art: *helen_art
  fake     : !JOIN [*IMAGE_FOLDER, "fake.gif"]
  tang     : !JOIN [*IMAGE_FOLDER, "tang.jpg"]
  scared   : !JOIN [*IMAGE_FOLDER, "scared.jpg"]
  chen     : !JOIN [*IMAGE_FOLDER, "chen_heal.png"]
  flaming  : !JOIN [*IMAGE_FOLDER, "flaming.jpg"]
  you_bad  : !JOIN [*IMAGE_FOLDER, "you_bad.png"]
  ck_lewd  : !JOIN [*IMAGE_FOLDER, "ck_lewd.jpg"]
  arkn     : !JOIN [*IMAGE_FOLDER, "arkn_materials.png"]
  trap_card: !JOIN [*IMAGE_FOLDER, "helen_trap_card.gif"]
  make_friends:
    - !JOIN [*IMAGE_FOLDER, "make_friends.jpg"]
    - !JOIN [*IMAGE_FOLDER, "make_friends_gg.jpg"]
    - !JOIN [*IMAGE_FOLDER, "make_friends_gg_thicc.jpg"]
  so_hot:
    - !JOIN [*IMAGE_FOLDER, "so_hot.jpg"]
    - !JOIN [*IMAGE_FOLDER, "so_hot_sumei.png"]
  magic_conch:
    kw:
      - !JOIN [*IMAGE_FOLDER, "magic_conch_why.jpg"]
      - !JOIN [*IMAGE_FOLDER, "magic_conch_wow.jpg"]
      - !JOIN [*IMAGE_FOLDER, "magic_conch_sus.jpg"]
    ask:
      - !JOIN [*IMAGE_FOLDER, "magic_conch_yes.png"]
      - !JOIN [*IMAGE_FOLDER, "magic_conch_no.png"]
  idk:
    - - !JOIN [*IMAGE_FOLDER, "idk_orig.jpg"]
      - 30
    - - !JOIN [*IMAGE_FOLDER, "idk_kailiu.jpg"]
      - 20
    - - !JOIN [*IMAGE_FOLDER, "idk_too.jpg"]
      - 15
    - - !JOIN [*IMAGE_FOLDER, "idk_flaming.jpg"]
      - 10
    - - !JOIN [*IMAGE_FOLDER, "idk_whatever.jpg"]
      - 10
    - - !JOIN [*IMAGE_FOLDER, "idk_ero.jpg"]
      - 10
    - - !JOIN [*IMAGE_FOLDER, "idk_gif.gif"]
      - 5
  yeah:
    - !JOIN [*IMAGE_FOLDER, "yeah.jpg"]
    - !JOIN [*IMAGE_FOLDER, "yeah_no.jpg"]
    - !JOIN [*IMAGE_FOLDER, "yeah_san_xiao.jpg"]
    - !JOIN [*IMAGE_FOLDER, "yeah_starburst.jpg"]
  mentioned_reply:
    - "蛤"
    - "笑死"
    - "嗷？"
    - "噁男"
    - "變態"
    - "ㄐㄐ"
    - "ouo"
    - "嘎嘎嘎"
    - "狐尼狐尼"
    - "黑洞黑洞"
    - "撒嬌撒嬌"
    - "窩不知道…"
    - "嗷嗷嗷嗷嗷"
    - "嘿嘿嘿嘿嘿"
    - ":thinking:"
    - "¯\\_(ツ)_/¯"
    - *helen_2
    - *helen_3
    - *helen_5
    - *helen_6
    - *helen_7
    - !JOIN ["我就爛 ", *pepe_hypers]
    - !JOIN ["我想要那個 donut ", *helen_4]
    - !JOIN ["給我那個 donut 好嗎 ", *helen_1]
  act_cute:
    - *helen_1
    - *helen_2
    - *helen_3
    - *helen_4
    - *helen_5
    - *helen_6
    - *helen_7
  helen_cards:
    - !JOIN [*IMAGE_FOLDER, "helen_black_mage.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_blue_eye_dragon.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_eagle.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_exodia.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_giant.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_girl.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_god_dragon.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_kaleidoscope.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_lion.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_master.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_party.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_pot.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_pot2.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_reflect.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_revive.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_sisters.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_sky_dragon.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_sword.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_warrior.png"]
    - !JOIN [*IMAGE_FOLDER, "helen_water.png"]
  loading_cat:
    - !JOIN [
        "<:ldc_01:725343128986320916>",
        "<:ldc_02:725343129011486761>",
        "<:ldc_03:725343129183584367>",
        "<:ldc_04:725343129011748976>",
        "<:ldc_05:725343128604770348>",
      ]
    - !JOIN [
        "<:ldc_06:725343128910954547>",
        "<:ldc_07:725343128839520259>",
        "<a:ldc_08:725343129892552764>",
        "<:ldc_09:725343129011617852>",
        "<:ldc_10:725343128986583059>",
      ]
    - !JOIN [
        "<:ldc_11:725343129087115374>",
        "<:ldc_12:725343128818548737>",
        "<:ldc_13:725343128822743041>",
        "<:ldc_14:725343128994840657>",
        "<:ldc_15:725343129003360346>",
      ]
  meals:
    - "旋轉薯條"
    - "路滷味"
    - "啾啾套餐"
    - "野狗冬瓜檸檬"
    - "鐵板啾啾牛肉套餐"
    - "炒飯＋優格"
    - "蜂蜜啾啾優格"
    - "蜂蜜蛋糕炒飯"
    - "椰漿飯蛋糕"
    - "柳連咖啡披薩"
    - "啾啾蓓蕾炒飯"
    - "八冰綠茶泡飯"
    - "肯德基"
    - "麥外勞"
    - "丹丹漢堡"
    - "香腸大火"

fun:
  bzz:
    options: &BZZ_OPTIONS
      - "大凶"
      - "小凶"
      - "凶"
      - "平"
      - "吉"
      - "小吉"
      - "大吉"
      - "吉掰"
      - "大吉掰"
      - *i11_chiwawa
  tdbzz:
    options: *BZZ_OPTIONS

tasks:
  left_ten_seconds: !JOIN [*IMAGE_FOLDER, "left_ten_seconds.png"]
  left_three_hours: !JOIN [*IMAGE_FOLDER, "left_three_hours.jpg"]
  three_oclock    : !JOIN [*IMAGE_FOLDER, "three_oclock.png"]
